name: Build Windows Server 2019

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-2019

    steps:
    - name: Download eCAL
      uses: robinraju/release-downloader@v1.5
      with:
        repository: "eclipse-ecal/ecal"
        latest: true
        fileName: "ecal_*-win64.exe"
        
    - name: Install eCAL
      run: |
        START /W ecal_*-win64.exe /SILENT /ALLUSERS /SUPPRESSMSGBOXES /NORESTART /TYPE=full
      shell: cmd

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules:  'true'
        fetch-depth: 0
        
    - name: Cmake
      run: |
        mkdir _build
        cd _build
        SET
        dir /s C:\eCAL\lib
        cmake -G "Visual Studio 16 2019" -Tv140 -Ax64 -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON -DCMAKE_PREFIX_PATH="C:/eCAL/lib/cmake/eCAL" -DCMAKE_MODULE_PATH="C:/eCAL/lib/cmake/eCAL" ..
      shell: cmd
