name: Build Windows Server 2019

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-2019

    steps:
    - name: Download eCAL
      uses: robinraju/release-downloader@v1.5
      with:
        repository: "eclipse-ecal/ecal"
        latest: true
        filname: "ecal_*-win64.exe"
        

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules:  'true'
        fetch-depth: 0
