name: Build Windows Server 2019

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-2019

    steps:
    - name: Download eCAL
      run: Invoke-WebRequest https://github.com/eclipse-ecal/ecal/releases/download/v5.10.2/ecal_5.10.2-win64.exe -OutFile ecal_5.10.2-win64.exe

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules:  'true'
        fetch-depth: 0
